### ISSUE TITLE
Cannot assign to read only property 'exports' of object '#<Object>'

### ISSUE THREAD

**Issue by lxc455735702** [cube-ui/cube-nuxt-demo#1]
本地克隆的项目已经ok ，然后想在nuxt 自己的项目去接入的时候。打开网页的时候报错 
Cannot assign to read only property 'exports' of object '#<Object>'
然后对比一下nuxt.config.js
把 module.exports = {} 变成 export default{}的时候报错  SyntaxError: Unexpected token export

求解：
我刚接触web es6等语法不太清楚。希望解答

**Comment by lxc455735702** [comment]
```
(function webpackUniversalModuleDefinition(root, factory) {
	if(typeof exports === 'object' && typeof module === 'object')
		module.exports = factory();
	else if(typeof define === 'function' && define.amd)
		define([], factory);
	else if(typeof exports === 'object')
```

**Comment by lxc455735702** [comment]
初始化项目配置koa

**Comment by helongliang** [comment]
> 初始化项目配置koa

遇到了同样的问题，意思是cube-ui初始化必需要用koa吗

**Comment by helongliang** [comment]
请问nuxt怎么按需引入cube-ui，你引入成功了吗

**Comment by helongliang** [comment]
请问nuxt怎么按需引入cube-ui，你引入成功了吗，我也遇到这个问题了，不知道怎么解决

**Comment by lxc455735702** [comment]
> 请问nuxt怎么按需引入立体UI，你引入成功了吗，我也遇到这个问题了，不知道怎么解决

这个项目示例本身就是按需引入。
初始化项目的时候先不要配置koa  选择none 你再试试

**Comment by fx1422** [comment]
这个问题怎么解决的，我也遇到了

**Comment by lxc455735702** [comment]
> 这个问题怎么解决的，我也遇到了

你创建项目的时候配置了什么？你最好有些都是none 用最简单的创建项目。应该可以的
